# Generated by Django 3.2.13 on 2022-08-15 16:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_membership_payhistory_subscription_usermembership_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='verification_expires',
            field=models.DateField(default=datetime.date(2022, 8, 18)),
        ),
        migrations.AlterField(
            model_name='payhistory',
            name='user',
            field=models.ForeignKey(null=None, on_delete=django.db.models.deletion.CASCADE, to='users.newuser'),
        ),
    ]
