# Generated by Django 3.2.13 on 2022-09-08 02:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_membership_membership_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='verification_expires',
            field=models.DateField(default=datetime.date(2022, 9, 11)),
        ),
    ]
