# Generated by Django 3.2.13 on 2022-09-09 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_newuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='verification_expires',
            field=models.DateField(default=datetime.date(2022, 9, 12)),
        ),
    ]
