# Generated by Django 3.2.13 on 2022-09-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subs', '0005_auto_20220915_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistinfo',
            name='art_followers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artistinfo',
            name='art_popularity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
