# Generated by Django 3.2.13 on 2022-09-15 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Subs', '0006_auto_20220915_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistinfo',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artInfo', to='Subs.artist'),
        ),
    ]
