# Generated by Django 3.2.13 on 2022-05-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='track_Name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='track_No',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='track_Popularity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='track_Type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='track_discNo',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='track_duration',
            field=models.BigIntegerField(null=True),
        ),
    ]
