# Generated by Django 3.2.13 on 2022-05-10 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotAPI', '0002_auto_20220510_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='art_HREF',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='art_Name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='art_Popularity',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='art_URI',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='art_followers',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='art_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
