# Generated by Django 3.2.13 on 2022-05-10 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spotAPI', '0003_auto_20220511_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='alb_ID',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='spotAPI.album'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='trackID',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='spotAPI.track'),
        ),
    ]
