# Generated by Django 3.2.13 on 2022-05-11 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spotAPI', '0004_auto_20220511_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='alb_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spotAPI.album'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='trackID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spotAPI.track'),
        ),
    ]
