# Generated by Django 3.2.13 on 2022-05-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotAPI', '0005_auto_20220511_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='alb_ReleaseDate',
            field=models.CharField(max_length=50),
        ),
    ]
